exclude: "(?x)^(.*/base/charts/.*)"
repos:
  # general stuff
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # Git style
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules
      - id: no-commit-to-branch

      # Common errors
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
        exclude: "(?x)^(.*/delete-.*.yaml)"
      - id: check-merge-conflict
      - id: check-executables-have-shebangs

  # security scans for infrastructure
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: "2.0.1037"
    hooks:
      - id: checkov

  # scanning for terraform issues
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
      - id: terraform_tfsec
